name: Deploy

on:
  push:
    branches:
      - '*'
  pull_request:
    types: [ closed ]
    branches:
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'npm'
      - name: Install
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test

  deploy:
    name: Deploy
    needs:
      - build
      - test
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: ./dist
